# Generated by Django 3.2.9 on 2021-12-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Communautaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('period_commencement', models.CharField(blank=True, max_length=255, null=True)),
                ('periode_fin', models.CharField(blank=True, max_length=255, null=True)),
                ('nom_compagnie', models.CharField(blank=True, max_length=255, null=True)),
                ('pays', models.CharField(blank=True, max_length=255, null=True)),
                ('ville', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(blank=True, max_length=255, null=True)),
                ('debut_annee', models.IntegerField(blank=True)),
                ('fin_annee', models.IntegerField(blank=True)),
                ('nom_etablisement', models.CharField(blank=True, max_length=255, null=True)),
                ('pays', models.CharField(blank=True, max_length=255, null=True)),
                ('ville', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=255, null=True)),
                ('periode_commencement', models.CharField(blank=True, max_length=255, null=True)),
                ('periode_fin', models.CharField(blank=True, max_length=255, null=True)),
                ('nom_compagnie', models.CharField(blank=True, max_length=255, null=True)),
                ('pays', models.CharField(blank=True, max_length=255, null=True)),
                ('ville', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Item_portofolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('Application', 'Application'), ('Web', 'Web')], default='Application', max_length=255)),
                ('client', models.CharField(blank=True, max_length=255, null=True)),
                ('lien_projet', models.CharField(blank=True, max_length=255, null=True)),
                ('image_projet_1', models.ImageField(blank=True, upload_to='images/portfolio/')),
                ('image_projet_2', models.ImageField(blank=True, null=True, upload_to='images/portfolio/')),
                ('image_projet_3', models.ImageField(blank=True, null=True, upload_to='images/portfolio/')),
                ('detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('prenom', models.CharField(blank=True, max_length=255, null=True)),
                ('localisation', models.CharField(blank=True, max_length=255, null=True)),
                ('biographie', models.TextField()),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='images/profile/')),
                ('photo_arriere_plan', models.ImageField(blank=True, null=True, upload_to='images/background/')),
                ('lien_twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('lien_instagram', models.CharField(blank=True, max_length=255, null=True)),
                ('lien_linkedin', models.CharField(blank=True, max_length=255, null=True)),
                ('lien_github', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('numero_telephone', models.CharField(blank=True, max_length=255, null=True)),
                ('niveau_etude', models.CharField(blank=True, max_length=255, null=True)),
                ('date_anniversaire', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255)),
                ('capacite', models.IntegerField(blank=True)),
                ('categorie', models.CharField(choices=[('Technologie', 'Technologie'), ('Langage', 'Langage')], default='Langage', max_length=255)),
            ],
        ),
    ]
