# Generated by Django 3.2.9 on 2021-12-16 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item_portofolio',
            new_name='Item_portfolio',
        ),
        migrations.RenameField(
            model_name='profil',
            old_name='biographie',
            new_name='bio',
        ),
    ]
