# Generated by Django 4.0.5 on 2022-07-23 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_community_education_itemportfolio_profile_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
